#!/bin/bash
pid=`ps aux|grep '__PROCESSNAME__'|grep -v grep|grep -v vi|grep -v '__SELF__'|awk '{print $2}'`
if [ "" = "$pid" ];
then
	echo "0 0 0"	
    exit
fi
cpu_core=$(grep -c processor /proc/cpuinfo)
total_time1=$(awk '{if ($1 == "cpu") {sum = $2 + $3 + $4 + $5 + $6 + $7 + $8 + $9 + $10 + $11;print sum}}' /proc/stat)
cpu_time1=$(awk '{sum=$14 + $15;print sum}' /proc/$pid/stat)

sleep 3

total_time2=$(awk '{if ($1 == "cpu") {sum = $2 + $3 + $4 + $5 + $6 + $7 + $8 + $9 + $10 + $11;print sum}}' /proc/stat)
cpu_time2=$(awk '{sum=$14 + $15;print sum}' /proc/$pid/stat)
cpuuse=`awk -v cpu_time1=$cpu_time1 -v total_time1=$total_time1 -v cpu_time2=$cpu_time2 -v total_time2=$total_time2 -v cpu_core=$cpu_core 'BEGIN{cpu=((cpu_time2 - cpu_time1) / (total_time2 - total_time1)) * 100*cpu_core;print cpu}'`
	
mem=`cat /proc/$pid/status|grep -e VmRSS|awk '{print $2}'`
fsthreads=`ps -mq $pid|wc -l`
#echo "MemUsed: $(($mem/1024)) MB  cpu: $cpuuse%  fsthreads=$fsthreads "
echo $(($mem/1024)) $cpuuse $fsthreads
